import type { Metadata } from "next";
import { SiteHeader } from "@/components/sections/SiteHeader/SiteHeader";
import { SiteFooter } from "@/components/sections/SiteFooter/SiteFooter";
import { Closing, RouteHero } from "@/components/sections/route/RouteSections";
import { SectionLabel } from "@/components/ui/SectionLabel/SectionLabel";
import { ActionLink } from "@/components/ui/ActionLink/ActionLink";
import { Reveal } from "@/components/ui/Reveal/Reveal";
import styles from "@/components/sections/route/RouteSections.module.css";

export const metadata: Metadata = { title: "Work & Credibility", description: "Documented CrimsonTide work, sector relevance, and client relationships." };
const sectors = ["Retail & Supermarkets", "Financial Institutions & Banks", "Hospitality, Tourism & Airports", "Public Sector & Institutions", "Distribution & Warehousing"];
export default function WorkPage() { return <><SiteHeader /><main id="main-content" tabIndex={-1}>
  <RouteHero id="work-heading" label="Work & Credibility" title="Experience is proven in practice" description="Explore projects, industries, and organisations that form part of CrimsonTide's track record and show how technology is applied in real-world contexts." action={{ label: "View case studies", href: "#work-cases" }} />
  <section id="work-cases" className={styles.section}><div className={styles.container}><Reveal className={styles.intro}><SectionLabel>Case studies</SectionLabel><h2>From real-world context to applied technology.</h2><p>General Food Supermarket, Liguanea</p></Reveal><Reveal className={styles.item}><p className={styles.kicker}>Retail · Implementation</p><h3>AI-enabled camera technology in a working supermarket environment.</h3><p>CrimsonTide worked with General Food Supermarket in Liguanea on an AI-enabled camera technology implementation designed to support security, loss prevention, and greater visibility across operations.</p><p>The implementation covered operational areas including cashier zones. Analytical capabilities were introduced to observe activity, behaviour, and operational patterns.</p><ul><li>Support loss prevention and security.</li><li>Increase visibility into activity and operational patterns.</li><li>Provide information to support operational and customer-experience decisions.</li></ul></Reveal></div></section>
  <section id="work-industries" className={styles.section}><div className={styles.container}><Reveal className={styles.intro}><SectionLabel>Industries</SectionLabel><h2>Different environments. Different challenges.</h2><p>Technology creates value when it responds to the context in which it operates.</p></Reveal><div className={styles.threeItems}>{sectors.map((sector, index) => <Reveal key={sector} className={styles.item}><span className={styles.index}>0{index + 1}</span><h3>{sector}</h3><p>{index === 0 ? "Security, loss prevention, operational visibility, and analysis relevant to retail environments." : "Technology that can adapt to the specific security, operational visibility, and decision-making needs of this environment."}</p></Reveal>)}</div><ActionLink href="/solutions">Explore solutions for your sector</ActionLink></div></section>
  <section id="work-clients" className={styles.section}><div className={styles.container}><Reveal className={styles.intro}><SectionLabel>Clients & partnerships</SectionLabel><h2>Credibility is also built through real relationships.</h2><p>Organisations and relationships that form part of CrimsonTide&apos;s experience.</p></Reveal><div className={styles.threeItems}>{["General Food Supermarket", "Guardsman Group", "Beryllium"].map((name, index) => <Reveal className={styles.item} key={name}><span className={styles.index}>0{index + 1}</span><h3>{name}</h3><p>{index === 0 ? "Retail client and documented Liguanea case study." : "Client relationship."}</p></Reveal>)}</div></div></section>
  <Closing title="Turn experience into what comes next." description="Whether you are exploring an opportunity, expanding capabilities, or looking for technology built around a specific context, let&apos;s discuss what CrimsonTide can build with you." />
</main><SiteFooter /></>; }
